### ISSUE TITLE
Style white/black cards in inline winning message

### ISSUE THREAD

**Issue by berrycardsagainsthumanity** [berrycardsagainsthumanity/cah#14]

**Comment by pao** [comment]
As-is, this would need to be done by adding `<span>`s in `game.py`, since that's where the string is substituted. Maybe that logic should be moved to JS, assuming ICanHaz/JQuery can do something for us?

**Comment by berrycardsagainsthumanity** [comment]
At the very least we could do some kind of string formatting in the Javascript using regex. The client side templating is very limited in what it can do, but if we gave it an array of dictionaries with text and css class it could spit out the right html.

**Comment by berrycardsagainsthumanity** [comment]
I was thinking about this further. I think putting the span in on the server side wouldn't be a good solution because it would imply the chat box could get html messages on the pub/sub channel, opening it up to all kinds of script injection nastiness. I think I'll add a new channel to publish messages on and send the message in a format that the templating can handle.

**Comment by pao** [comment]
Agreed, though I wasn't thinking about the security implications.

We still have the problem that part of the template is the dynamic card text.

**Comment by berrycardsagainsthumanity** [comment]
I have a decent solution around the templating portion, but wrangling the punctuation and stuff is taking some time. I'll probably have something out tonight. And unit tests are very good for this kind of thing. :D

**Comment by berrycardsagainsthumanity** [comment]
Fixed in af901f9
