### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by pao** [berrycardsagainsthumanity/cah#16]
Unit tests, etc.

This looks maybe useful for coordinating full-up tests: http://thrilljs.com/

**Comment by berrycardsagainsthumanity** [comment]
I added a unit test last night to test the draw 2 feature. I'll probably just stick with server side unit tests for now.

**Comment by berrycardsagainsthumanity** [comment]
Gonna close this for now. Now that I've got the testing framework in place I'll be adding tests as I go along.
