### ISSUE TITLE
AFK/czar players shouldn't draw

### ISSUE THREAD

**Issue by pao** [berrycardsagainsthumanity/cah#27]
This comes up when a Draw 2, Pick 3 card happens.

**Comment by pao** [comment]
More server-side checks will be involved, I suspect.

**Comment by pao** [comment]
This is actually a little more subtle--if an AFK player comes out of AFK, ideally they'll draw the extra cards at that time. If a non-AFK player fails to play, ideally they'll be asked to discard back down to 10 before resuming play.

**Comment by berrycardsagainsthumanity** [comment]
Probably no need to worry about getting them to draw extra cards or discarding, it's such an edge case. But yeah, afk/czar shouldn't draw extra
