### ISSUE TITLE
Touch compatibility

### ISSUE THREAD

**Issue by pao** [berrycardsagainsthumanity/cah#4]
Can't double-click on mobile browsers. Not sure of good solution.

**Comment by pao** [comment]
Perhaps pop up a confirm button on single click (tap). Need single click and double click to be exclusive events for that to work.

**Comment by pao** [comment]
[FastClick](https://github.com/ftlabs/fastclick) might be a good idea too.

**Comment by pao** [comment]
Actually, I think [we have a winner](https://github.com/benmajor/jQuery-Mobile-Events). Working on it.

**Comment by berrycardsagainsthumanity** [comment]
Nice, that looks awesome!
