### ISSUE TITLE
Use Autobahn's IResource interface

### ISSUE THREAD

**Issue by pao** [berrycardsagainsthumanity/cah#41]
Work item for another (slight) refactoring. This might come for free out of https://github.com/pao/cah/tree/topic/openshift.

With this in place we should be able to run the whole game on a single port.

See https://github.com/tavendo/AutobahnPython/blob/master/examples/websocket/echo_site/server.py

**Comment by pao** [comment]
I have this working on my topic/openshift branch. Unfortunately that isn't quite enough to get things working on OpenShift, whose websocket support is very new. I've hit up the OpenShift forums for help.

If you think this is worthwhile to bring over independently, I can split this out separately.

**Comment by berrycardsagainsthumanity** [comment]
Running on a single port would be awesome - it would clearup some issues with people behind firewalls and possible some mobile issues.

**Comment by pao** [comment]
OK
